[workspace]

resolver = "2"

members = [
    "ovh-api",
    "x-deploy-cli",
    "x-deploy-client",
    "xdeploy-api",
]

[workspace.dependencies]
futures = "0.3.28"
log = "0.4.20"
serde = { version = "1.0.188", features = ["derive"] }
tokio = { version = "1.32.0", features = ["full"] }
serde_json = "1.0.107"
