[workspace]

resolver = "2"
members = [
    "ovh-api", "xdeploy-api",
]

[workspace.dependencies]
env_logger = "0.10.0"
futures = "0.3.28"
log = "0.4.20"
serde = { version = "1.0.188", features = ["derive"] }
serde_json = "1.0.107"
tokio = { version = "1.32.0", features = ["full"] }
