[package]
name = "xdeploy-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.10.0"
rocket = { version = "0.5.0-rc.3" }
ovh-api = { path = "../ovh-api" }
rocket_okapi = { version = "0.8.0-rc.3", features = ["rapidoc", "swagger"] }
serde_yaml = "0.9.27"
serde = { workspace = true, features = ["derive"] }
kube = { version = "0.87.1", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.20.0", features = ["latest"] }
dotenv = "0.15.0"
mongodb = { version = "2.7.1", features = ["tokio-sync"] }
bson = "2.7.0"
redis = "0.23.3"
jsonwebtoken = "9.1.0"
bcrypt = "0.15.0"
lazy_static = "1.4.0"
log = "0.4.20"
