pub(crate) mod organization;
pub(crate) mod organization_apikey;
pub(crate) mod organization_custom_role;
pub(crate) mod organization_invitation;
pub(crate) mod organization_member;
pub(crate) mod ovh_credentials;
pub(crate) mod project;
pub(crate) mod query;
pub(crate) mod user;
